baseURL = 'https://marble.main.jp'
languageCode = 'ja'
title = 'Marble 公式サイト'

[params]
customCSS = [
  "/css/header.css",
  "/css/body.css",
  "/css/list_page.css",
  "/css/infotable.css",
  "/css/blog.css",
  "/css/footer.css",
]
author = "Marble Project"

[params.site]
copystart = "2022"
