baseURL = 'https://marble.main.jp'
languageCode = 'ja'
title = 'Marble 公式サイト'

[params]
customCSS = [
  "/css/header.css",
  "/css/infotable.css",
  "/css/custom.css",
  "/css/footer.css",
  "/css/body.css"
]
author = "Akira Kano (Aqun)"

[params.site]
copystart = "2022"
