name: lolipop

on:
  workflow_dispatch:
    inputs:
      product_os:
        description: "Product OS (e.g. Windows, Mac or All)"
        required: true
      product_version:
        description: "Product Version (e.g. x.x.x)"
        required: true
  repository_dispatch:
    types: [on-product-upgrade]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest

      - name: Build
        run: hugo --minify --baseURL http://marble.main.jp

      - name: Select Product Version
        if: ${{ !github.event.client_payload.from_release }}
        run: |
          echo "${PRODUCT_VERSION}"
        env:
          PRODUCT_VERSION: ${{ github.event.inputs.product_version }}

      - name: Check Env
        run: |
          echo "${PRODUCT_VERSION}"

      - name: OS Validation
        if: ${{ github.event.inputs.product_os }} != "All" && \
            ${{ github.event.inputs.product_os }} != "Windows" && \
            ${{ github.event.inputs.product_os }} != "Mac"
        run: | 
          echo "Cannot pass. Input OS is ${{ github.event.inputs.product_os }}."
          exit 1

      - name: Fetch Product for Windows
        if: ${{ github.event.inputs.product_os }} == "All" || ${{ github.event.inputs.product_os }} == "Windows"
        run: |
          curl -sLJO -H 'Accept: application/octet-stream' \
            "https://${{ secrets.RECIPE_NOTE_TOKEN }}@api.github.com/repos/kano1101/recipe_note/releases/assets/$( \
              curl -sL https://${{ secrets.RECIPE_NOTE_TOKEN }}@api.github.com/repos/kano1101/recipe_note/releases/tags/v${PRODUCT_VERSION} \
                | jq '.assets[] | select(.name | contains("Windows")) | .id')"

      - name: Fetch Product for Mac
        if: ${{ github.event.inputs.product_os }} == "All" || ${{ github.event.inputs.product_os }} == "Mac"
        run: |
          curl -sLJO -H 'Accept: application/octet-stream' \
            "https://${{ secrets.RECIPE_NOTE_TOKEN }}@api.github.com/repos/kano1101/recipe_note/releases/assets/$( \
              curl -sL https://${{ secrets.RECIPE_NOTE_TOKEN }}@api.github.com/repos/kano1101/recipe_note/releases/tags/${PRODUCT_VERSION} \
                | jq '.assets[] | select(.name | contains("Mac")) | .id')"

      - name: Display Directory
        run: 
          ls -al .

      - name: Move Product
        run: |
          mv ./Marble-for-* public/

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@3.0.0
        with:
          ftp-server: ${{ secrets.FTP_HOST }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          git-ftp-args: --remote-root ${{ secrets.FTP_REMOTE_ROOT }}
          local-dir: public
