name: lolipop

on:
  workflow_dispatch:
    inputs:
      product_version:
        description: "Product Version (e.g. x.x.x)"
        required: true
  repository_dispatch:
    types: [on-product-upgrade]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      MANUAL_VERSION: ${{ github.event.inputs.product_version }}
      AUTO_VERSION: ${{ github.event.client_payload.product_version }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Decide release product
        run: |
          if [ ! -z $MANUAL_VERSION ] && [ -z $AUTO_VERSION ]; then
            echo "RELEASE_VERSION=$MANUAL_VERSION" >> $GITHUB_ENV
          fi
          if [ ! -z $AUTO_VERSION ] && [ -z $MANUAL_VERSION ]; then
            echo "RELEASE_VERSION=$AUTO_VERSION" >> $GITHUB_ENV
          fi

      - name: Assert release require
        run: |
          if [ -z $RELEASE_OS ] || [ -z $RELEASE_VERSION ]; then
            exit 11
          fi

      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest

      - name: Build
        run: hugo --minify --baseURL https://marble.main.jp

      - name: Check Env
        run: |
          echo "MANUAL_VERSION=${MANUAL_VERSION}"
          echo "AUTO_VERSION=${AUTO_VERSION}"
          echo "RELEASE_VERSION=${RELEASE_VERSION}"

      - name: Make Directory
        run: |
          mkdir -p download

      - name: Fetch Product
        run: |
          cd download/
          curl -sLJO -H 'Accept: application/octet-stream' \
            "https://${{ secrets.RECIPE_NOTE_TOKEN }}@api.github.com/repos/kano1101/recipe_note/releases/assets/$( \
              curl -sL https://${{ secrets.RECIPE_NOTE_TOKEN }}@api.github.com/repos/kano1101/recipe_note/releases/tags/v${RELEASE_VERSION} \
                | jq '.assets[] | select(.name | contains("Windows")) | .id')"
          curl -sLJO -H 'Accept: application/octet-stream' \
            "https://${{ secrets.RECIPE_NOTE_TOKEN }}@api.github.com/repos/kano1101/recipe_note/releases/assets/$( \
              curl -sL https://${{ secrets.RECIPE_NOTE_TOKEN }}@api.github.com/repos/kano1101/recipe_note/releases/tags/v${RELEASE_VERSION} \
                | jq '.assets[] | select(.name | contains("Mac")) | .id')"

      - name: Display Directory
        run: |
          echo "in root directory"
          ls -al .
          echo "in download directory"
          ls -al ./download

      - name: Move Product
        run: |
          mv ./download public/

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@3.0.0
        with:
          ftp-server: ${{ secrets.FTP_HOST }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          git-ftp-args: --remote-root ${{ secrets.FTP_REMOTE_ROOT }}
          local-dir: public
